#ChipScope Core Inserter Project File Version 3.0
#Thu Sep 05 20:29:03 CST 2013
Project.device.designInputFile=F\:\\13\\GroundSystem\\code\\V2\\ground_pro_all\\ground_pro_top_cs.ngc
Project.device.designOutputFile=F\:\\13\\GroundSystem\\code\\V2\\ground_pro_all\\ground_pro_top_cs.ngc
Project.device.deviceFamily=17
Project.device.enableRPMs=true
Project.device.outputDirectory=F\:\\13\\GroundSystem\\code\\V2\\ground_pro_all\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=14
Project.filter<0>=
Project.filter<10>=*REG*
Project.filter<11>=*cur*
Project.filter<12>=*time*
Project.filter<13>=*clk*
Project.filter<1>=**
Project.filter<2>=*dq*
Project.filter<3>=*
Project.filter<4>=*cnt*
Project.filter<5>=*re*
Project.filter<6>=*rst*
Project.filter<7>=*fifo*
Project.filter<8>=*ok*
Project.filter<9>=*GPS*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=Inst_CRG sys_clk_80M
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=Inst_multichnlTDC fifo_rst
Project.unit<0>.dataChannel<100>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<13>
Project.unit<0>.dataChannel<101>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<12>
Project.unit<0>.dataChannel<102>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<11>
Project.unit<0>.dataChannel<103>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<10>
Project.unit<0>.dataChannel<104>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<9>
Project.unit<0>.dataChannel<105>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<8>
Project.unit<0>.dataChannel<106>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<7>
Project.unit<0>.dataChannel<107>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<6>
Project.unit<0>.dataChannel<108>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<5>
Project.unit<0>.dataChannel<109>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<4>
Project.unit<0>.dataChannel<10>=Inst_multichnlTDC tdc_frame_fifo_inst dout<11>
Project.unit<0>.dataChannel<110>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<3>
Project.unit<0>.dataChannel<111>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<2>
Project.unit<0>.dataChannel<112>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<1>
Project.unit<0>.dataChannel<113>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<0>
Project.unit<0>.dataChannel<114>=Inst_multichnlTDC sdram_cpldif_fifo_inst rst
Project.unit<0>.dataChannel<115>=Inst_multichnlTDC sdram_cpldif_fifo_inst wr_clk
Project.unit<0>.dataChannel<116>=Inst_multichnlTDC sdram_cpldif_fifo_inst rd_clk
Project.unit<0>.dataChannel<117>=Inst_multichnlTDC sdram_cpldif_fifo_inst wr_en
Project.unit<0>.dataChannel<118>=Inst_multichnlTDC sdram_cpldif_fifo_inst rd_en
Project.unit<0>.dataChannel<119>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<31>
Project.unit<0>.dataChannel<11>=Inst_multichnlTDC tdc_frame_fifo_inst dout<10>
Project.unit<0>.dataChannel<120>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<30>
Project.unit<0>.dataChannel<121>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<29>
Project.unit<0>.dataChannel<122>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<28>
Project.unit<0>.dataChannel<123>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<27>
Project.unit<0>.dataChannel<124>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<26>
Project.unit<0>.dataChannel<125>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<25>
Project.unit<0>.dataChannel<126>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<24>
Project.unit<0>.dataChannel<127>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<23>
Project.unit<0>.dataChannel<128>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<22>
Project.unit<0>.dataChannel<129>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<21>
Project.unit<0>.dataChannel<12>=Inst_multichnlTDC tdc_frame_fifo_inst dout<9>
Project.unit<0>.dataChannel<130>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<20>
Project.unit<0>.dataChannel<131>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<19>
Project.unit<0>.dataChannel<132>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<18>
Project.unit<0>.dataChannel<133>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<17>
Project.unit<0>.dataChannel<134>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<16>
Project.unit<0>.dataChannel<135>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<15>
Project.unit<0>.dataChannel<136>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<14>
Project.unit<0>.dataChannel<137>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<13>
Project.unit<0>.dataChannel<138>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<12>
Project.unit<0>.dataChannel<139>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<11>
Project.unit<0>.dataChannel<13>=Inst_multichnlTDC tdc_frame_fifo_inst dout<8>
Project.unit<0>.dataChannel<140>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<10>
Project.unit<0>.dataChannel<141>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<9>
Project.unit<0>.dataChannel<142>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<8>
Project.unit<0>.dataChannel<143>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<7>
Project.unit<0>.dataChannel<144>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<6>
Project.unit<0>.dataChannel<145>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<5>
Project.unit<0>.dataChannel<146>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<4>
Project.unit<0>.dataChannel<147>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<3>
Project.unit<0>.dataChannel<148>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<2>
Project.unit<0>.dataChannel<149>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<1>
Project.unit<0>.dataChannel<14>=Inst_multichnlTDC tdc_frame_fifo_inst dout<7>
Project.unit<0>.dataChannel<150>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<0>
Project.unit<0>.dataChannel<151>=Inst_cpld_if tdc_cpldif_fifo_wr_data<31>
Project.unit<0>.dataChannel<152>=Inst_cpld_if tdc_cpldif_fifo_wr_data<30>
Project.unit<0>.dataChannel<153>=Inst_cpld_if tdc_cpldif_fifo_wr_data<29>
Project.unit<0>.dataChannel<154>=Inst_cpld_if tdc_cpldif_fifo_wr_data<28>
Project.unit<0>.dataChannel<155>=Inst_cpld_if tdc_cpldif_fifo_wr_data<27>
Project.unit<0>.dataChannel<156>=Inst_cpld_if tdc_cpldif_fifo_wr_data<26>
Project.unit<0>.dataChannel<157>=Inst_cpld_if tdc_cpldif_fifo_wr_data<25>
Project.unit<0>.dataChannel<158>=Inst_cpld_if tdc_cpldif_fifo_wr_data<24>
Project.unit<0>.dataChannel<159>=Inst_cpld_if tdc_cpldif_fifo_wr_data<23>
Project.unit<0>.dataChannel<15>=Inst_multichnlTDC tdc_frame_fifo_inst dout<6>
Project.unit<0>.dataChannel<160>=Inst_cpld_if tdc_cpldif_fifo_wr_data<22>
Project.unit<0>.dataChannel<161>=Inst_cpld_if tdc_cpldif_fifo_wr_data<21>
Project.unit<0>.dataChannel<162>=Inst_cpld_if tdc_cpldif_fifo_wr_data<20>
Project.unit<0>.dataChannel<163>=Inst_cpld_if tdc_cpldif_fifo_wr_data<19>
Project.unit<0>.dataChannel<164>=Inst_cpld_if tdc_cpldif_fifo_wr_data<18>
Project.unit<0>.dataChannel<165>=Inst_cpld_if tdc_cpldif_fifo_wr_data<17>
Project.unit<0>.dataChannel<166>=Inst_cpld_if tdc_cpldif_fifo_wr_data<16>
Project.unit<0>.dataChannel<167>=Inst_cpld_if tdc_cpldif_fifo_wr_data<15>
Project.unit<0>.dataChannel<168>=Inst_cpld_if tdc_cpldif_fifo_wr_data<14>
Project.unit<0>.dataChannel<169>=Inst_cpld_if tdc_cpldif_fifo_wr_data<13>
Project.unit<0>.dataChannel<16>=Inst_multichnlTDC tdc_frame_fifo_inst dout<5>
Project.unit<0>.dataChannel<170>=Inst_cpld_if tdc_cpldif_fifo_wr_data<12>
Project.unit<0>.dataChannel<171>=Inst_cpld_if tdc_cpldif_fifo_wr_data<11>
Project.unit<0>.dataChannel<172>=Inst_cpld_if tdc_cpldif_fifo_wr_data<10>
Project.unit<0>.dataChannel<173>=Inst_cpld_if tdc_cpldif_fifo_wr_data<9>
Project.unit<0>.dataChannel<174>=Inst_cpld_if tdc_cpldif_fifo_wr_data<8>
Project.unit<0>.dataChannel<175>=Inst_cpld_if tdc_cpldif_fifo_wr_data<7>
Project.unit<0>.dataChannel<176>=Inst_cpld_if tdc_cpldif_fifo_wr_data<6>
Project.unit<0>.dataChannel<177>=Inst_cpld_if tdc_cpldif_fifo_wr_data<5>
Project.unit<0>.dataChannel<178>=Inst_cpld_if tdc_cpldif_fifo_wr_data<4>
Project.unit<0>.dataChannel<179>=Inst_cpld_if tdc_cpldif_fifo_wr_data<3>
Project.unit<0>.dataChannel<17>=Inst_multichnlTDC tdc_frame_fifo_inst dout<4>
Project.unit<0>.dataChannel<180>=Inst_cpld_if tdc_cpldif_fifo_wr_data<2>
Project.unit<0>.dataChannel<181>=Inst_cpld_if tdc_cpldif_fifo_wr_data<1>
Project.unit<0>.dataChannel<182>=Inst_cpld_if tdc_cpldif_fifo_wr_data<0>
Project.unit<0>.dataChannel<183>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<10>
Project.unit<0>.dataChannel<184>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<9>
Project.unit<0>.dataChannel<185>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<8>
Project.unit<0>.dataChannel<186>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<7>
Project.unit<0>.dataChannel<187>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<6>
Project.unit<0>.dataChannel<188>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<5>
Project.unit<0>.dataChannel<189>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<4>
Project.unit<0>.dataChannel<18>=Inst_multichnlTDC tdc_frame_fifo_inst dout<3>
Project.unit<0>.dataChannel<190>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<3>
Project.unit<0>.dataChannel<191>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<2>
Project.unit<0>.dataChannel<192>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<1>
Project.unit<0>.dataChannel<193>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<0>
Project.unit<0>.dataChannel<194>=Inst_multichnlTDC Inst_FramePack syn_frm_cnt<1>
Project.unit<0>.dataChannel<195>=Inst_multichnlTDC Inst_FramePack syn_frm_cnt<0>
Project.unit<0>.dataChannel<196>=Inst_multichnlTDC Inst_FramePack data_length_frm_cnt<1>
Project.unit<0>.dataChannel<197>=Inst_multichnlTDC Inst_FramePack data_length_frm_cnt<0>
Project.unit<0>.dataChannel<198>=Inst_multichnlTDC Inst_FramePack crc_frm_cnt<1>
Project.unit<0>.dataChannel<199>=Inst_multichnlTDC Inst_FramePack crc_frm_cnt<0>
Project.unit<0>.dataChannel<19>=Inst_multichnlTDC tdc_frame_fifo_inst dout<2>
Project.unit<0>.dataChannel<1>=Inst_multichnlTDC tdc_frame_fifo_inst rst
Project.unit<0>.dataChannel<200>=Inst_multichnlTDC Inst_FramePack end_frm_cnt<1>
Project.unit<0>.dataChannel<201>=Inst_multichnlTDC Inst_FramePack end_frm_cnt<0>
Project.unit<0>.dataChannel<202>=Inst_multichnlTDC Inst_FramePack crc_rst_n
Project.unit<0>.dataChannel<203>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<0>
Project.unit<0>.dataChannel<204>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<1>
Project.unit<0>.dataChannel<205>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<2>
Project.unit<0>.dataChannel<206>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<3>
Project.unit<0>.dataChannel<207>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<4>
Project.unit<0>.dataChannel<208>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<5>
Project.unit<0>.dataChannel<209>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<6>
Project.unit<0>.dataChannel<20>=Inst_multichnlTDC tdc_frame_fifo_inst dout<1>
Project.unit<0>.dataChannel<210>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<7>
Project.unit<0>.dataChannel<211>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<8>
Project.unit<0>.dataChannel<212>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<9>
Project.unit<0>.dataChannel<213>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<10>
Project.unit<0>.dataChannel<214>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<11>
Project.unit<0>.dataChannel<215>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd1-In
Project.unit<0>.dataChannel<216>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd2-In
Project.unit<0>.dataChannel<217>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In
Project.unit<0>.dataChannel<218>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In1
Project.unit<0>.dataChannel<219>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In2
Project.unit<0>.dataChannel<21>=Inst_multichnlTDC tdc_frame_fifo_inst dout<0>
Project.unit<0>.dataChannel<220>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In3
Project.unit<0>.dataChannel<221>=Inst_multichnlTDC Inst_FramePack tdc_frame_fifo_rd_en_sig
Project.unit<0>.dataChannel<222>=Inst_sysmonitor sysmon_cpldif_data<4>
Project.unit<0>.dataChannel<223>=Inst_sysmonitor sysmon_cpldif_data<3>
Project.unit<0>.dataChannel<224>=Inst_sysmonitor sysmon_cpldif_data<2>
Project.unit<0>.dataChannel<225>=Inst_sysmonitor sysmon_cpldif_data<1>
Project.unit<0>.dataChannel<226>=Inst_sysmonitor sysmon_cpldif_data<0>
Project.unit<0>.dataChannel<227>=Inst_sysmonitor sysmon_ram_rd_addr<3>
Project.unit<0>.dataChannel<228>=Inst_sysmonitor sysmon_ram_rd_addr<2>
Project.unit<0>.dataChannel<229>=Inst_sysmonitor sysmon_ram_rd_addr<1>
Project.unit<0>.dataChannel<22>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<15>
Project.unit<0>.dataChannel<230>=Inst_sysmonitor sysmon_ram_rd_addr<0>
Project.unit<0>.dataChannel<231>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<15>
Project.unit<0>.dataChannel<232>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<14>
Project.unit<0>.dataChannel<233>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<13>
Project.unit<0>.dataChannel<234>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<12>
Project.unit<0>.dataChannel<235>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<11>
Project.unit<0>.dataChannel<236>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<10>
Project.unit<0>.dataChannel<237>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<9>
Project.unit<0>.dataChannel<238>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<8>
Project.unit<0>.dataChannel<239>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<7>
Project.unit<0>.dataChannel<23>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<14>
Project.unit<0>.dataChannel<240>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<6>
Project.unit<0>.dataChannel<241>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<5>
Project.unit<0>.dataChannel<242>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<4>
Project.unit<0>.dataChannel<243>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<3>
Project.unit<0>.dataChannel<244>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<2>
Project.unit<0>.dataChannel<245>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<1>
Project.unit<0>.dataChannel<246>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<0>
Project.unit<0>.dataChannel<247>=Inst_TIME time_local_gps_cur<15>
Project.unit<0>.dataChannel<248>=Inst_TIME time_local_gps_cur<14>
Project.unit<0>.dataChannel<249>=Inst_TIME time_local_gps_cur<13>
Project.unit<0>.dataChannel<24>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<13>
Project.unit<0>.dataChannel<250>=Inst_TIME time_local_gps_cur<12>
Project.unit<0>.dataChannel<251>=Inst_TIME time_local_gps_cur<11>
Project.unit<0>.dataChannel<252>=Inst_TIME time_local_gps_cur<10>
Project.unit<0>.dataChannel<253>=Inst_TIME time_local_gps_cur<9>
Project.unit<0>.dataChannel<254>=Inst_TIME time_local_gps_cur<8>
Project.unit<0>.dataChannel<255>=Inst_TIME time_local_gps_cur<7>
Project.unit<0>.dataChannel<256>=Inst_TIME time_local_gps_cur<6>
Project.unit<0>.dataChannel<257>=Inst_TIME time_local_gps_cur<5>
Project.unit<0>.dataChannel<258>=Inst_TIME time_local_gps_cur<4>
Project.unit<0>.dataChannel<259>=Inst_TIME time_local_gps_cur<3>
Project.unit<0>.dataChannel<25>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<12>
Project.unit<0>.dataChannel<260>=Inst_TIME time_local_gps_cur<2>
Project.unit<0>.dataChannel<261>=Inst_TIME time_local_gps_cur<1>
Project.unit<0>.dataChannel<262>=Inst_TIME time_local_gps_cur<0>
Project.unit<0>.dataChannel<263>=Inst_TIME time_local_cur_sig<31>
Project.unit<0>.dataChannel<264>=Inst_TIME time_local_cur_sig<30>
Project.unit<0>.dataChannel<265>=Inst_TIME time_local_cur_sig<29>
Project.unit<0>.dataChannel<266>=Inst_TIME time_local_cur_sig<28>
Project.unit<0>.dataChannel<267>=Inst_TIME time_local_cur_sig<27>
Project.unit<0>.dataChannel<268>=Inst_TIME time_local_cur_sig<26>
Project.unit<0>.dataChannel<269>=Inst_TIME time_local_cur_sig<25>
Project.unit<0>.dataChannel<26>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<11>
Project.unit<0>.dataChannel<270>=Inst_TIME time_local_cur_sig<24>
Project.unit<0>.dataChannel<271>=Inst_TIME time_local_cur_sig<23>
Project.unit<0>.dataChannel<272>=Inst_TIME time_local_cur_sig<22>
Project.unit<0>.dataChannel<273>=Inst_TIME time_local_cur_sig<21>
Project.unit<0>.dataChannel<274>=Inst_TIME time_local_cur_sig<20>
Project.unit<0>.dataChannel<275>=Inst_TIME time_local_cur_sig<19>
Project.unit<0>.dataChannel<276>=Inst_TIME time_local_cur_sig<18>
Project.unit<0>.dataChannel<277>=Inst_TIME time_local_cur_sig<17>
Project.unit<0>.dataChannel<278>=Inst_TIME time_local_cur_sig<16>
Project.unit<0>.dataChannel<279>=Inst_TIME time_local_cur_sig<15>
Project.unit<0>.dataChannel<27>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<10>
Project.unit<0>.dataChannel<280>=Inst_TIME time_local_cur_sig<14>
Project.unit<0>.dataChannel<281>=Inst_TIME time_local_cur_sig<13>
Project.unit<0>.dataChannel<282>=Inst_TIME time_local_cur_sig<12>
Project.unit<0>.dataChannel<283>=Inst_TIME time_local_cur_sig<11>
Project.unit<0>.dataChannel<284>=Inst_TIME time_local_cur_sig<10>
Project.unit<0>.dataChannel<285>=Inst_TIME time_local_cur_sig<9>
Project.unit<0>.dataChannel<286>=Inst_TIME time_local_cur_sig<8>
Project.unit<0>.dataChannel<287>=Inst_TIME time_local_cur_sig<7>
Project.unit<0>.dataChannel<288>=Inst_TIME time_local_cur_sig<6>
Project.unit<0>.dataChannel<289>=Inst_TIME time_local_cur_sig<5>
Project.unit<0>.dataChannel<28>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<9>
Project.unit<0>.dataChannel<290>=Inst_TIME time_local_cur_sig<4>
Project.unit<0>.dataChannel<291>=Inst_TIME time_local_cur_sig<3>
Project.unit<0>.dataChannel<292>=Inst_TIME time_local_cur_sig<2>
Project.unit<0>.dataChannel<293>=Inst_TIME time_local_cur_sig<1>
Project.unit<0>.dataChannel<294>=Inst_TIME time_local_cur_sig<0>
Project.unit<0>.dataChannel<295>=Inst_TIME time_reg_given_l<31>
Project.unit<0>.dataChannel<296>=Inst_TIME time_reg_given_l<30>
Project.unit<0>.dataChannel<297>=Inst_TIME time_reg_given_l<29>
Project.unit<0>.dataChannel<298>=Inst_TIME time_reg_given_l<28>
Project.unit<0>.dataChannel<299>=Inst_TIME time_reg_given_l<27>
Project.unit<0>.dataChannel<29>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<8>
Project.unit<0>.dataChannel<2>=Inst_multichnlTDC tdc_frame_fifo_inst wr_clk
Project.unit<0>.dataChannel<300>=Inst_TIME time_reg_given_l<26>
Project.unit<0>.dataChannel<301>=Inst_TIME time_reg_given_l<25>
Project.unit<0>.dataChannel<302>=Inst_TIME time_reg_given_l<24>
Project.unit<0>.dataChannel<303>=Inst_TIME time_reg_given_l<23>
Project.unit<0>.dataChannel<304>=Inst_TIME time_reg_given_l<22>
Project.unit<0>.dataChannel<305>=Inst_TIME time_reg_given_l<21>
Project.unit<0>.dataChannel<306>=Inst_TIME time_reg_given_l<20>
Project.unit<0>.dataChannel<307>=Inst_TIME time_reg_given_l<19>
Project.unit<0>.dataChannel<308>=Inst_TIME time_reg_given_l<18>
Project.unit<0>.dataChannel<309>=Inst_TIME time_reg_given_l<17>
Project.unit<0>.dataChannel<30>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<7>
Project.unit<0>.dataChannel<310>=Inst_TIME time_reg_given_l<16>
Project.unit<0>.dataChannel<311>=Inst_TIME time_reg_given_l<15>
Project.unit<0>.dataChannel<312>=Inst_TIME time_reg_given_l<14>
Project.unit<0>.dataChannel<313>=Inst_TIME time_reg_given_l<13>
Project.unit<0>.dataChannel<314>=Inst_TIME time_reg_given_l<12>
Project.unit<0>.dataChannel<315>=Inst_TIME time_reg_given_l<11>
Project.unit<0>.dataChannel<316>=Inst_TIME time_reg_given_l<10>
Project.unit<0>.dataChannel<317>=Inst_TIME time_reg_given_l<9>
Project.unit<0>.dataChannel<318>=Inst_TIME time_reg_given_l<8>
Project.unit<0>.dataChannel<319>=Inst_TIME time_reg_given_l<7>
Project.unit<0>.dataChannel<31>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<6>
Project.unit<0>.dataChannel<320>=Inst_TIME time_reg_given_l<6>
Project.unit<0>.dataChannel<321>=Inst_TIME time_reg_given_l<5>
Project.unit<0>.dataChannel<322>=Inst_TIME time_reg_given_l<4>
Project.unit<0>.dataChannel<323>=Inst_TIME time_reg_given_l<3>
Project.unit<0>.dataChannel<324>=Inst_TIME time_reg_given_l<2>
Project.unit<0>.dataChannel<325>=Inst_TIME time_reg_given_l<1>
Project.unit<0>.dataChannel<326>=Inst_TIME time_reg_given_l<0>
Project.unit<0>.dataChannel<327>=Inst_TIME gps_pps_syn_pulse
Project.unit<0>.dataChannel<328>=Inst_TIME gps_pps_ok
Project.unit<0>.dataChannel<329>=Inst_TIME gps_pps_ok_cnt<1>
Project.unit<0>.dataChannel<32>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<5>
Project.unit<0>.dataChannel<330>=Inst_TIME gps_pps_ok_cnt<0>
Project.unit<0>.dataChannel<331>=Inst_multichnlTDC Chnl_2_inst fifo_rst
Project.unit<0>.dataChannel<332>=Inst_multichnlTDC Chnl_2_inst SysEnable
Project.unit<0>.dataChannel<333>=Inst_multichnlTDC Chnl_2_inst fifo_rst
Project.unit<0>.dataChannel<334>=Inst_multichnlTDC Chnl_2_inst Token_in
Project.unit<0>.dataChannel<335>=Inst_multichnlTDC Chnl_2_inst HitIn
Project.unit<0>.dataChannel<336>=Inst_multichnlTDC Chnl_2_inst ChnlFifoWrite
Project.unit<0>.dataChannel<337>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<48>
Project.unit<0>.dataChannel<338>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<47>
Project.unit<0>.dataChannel<339>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<46>
Project.unit<0>.dataChannel<33>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<4>
Project.unit<0>.dataChannel<340>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<45>
Project.unit<0>.dataChannel<341>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<44>
Project.unit<0>.dataChannel<342>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<43>
Project.unit<0>.dataChannel<343>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<42>
Project.unit<0>.dataChannel<344>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<41>
Project.unit<0>.dataChannel<345>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<40>
Project.unit<0>.dataChannel<346>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<39>
Project.unit<0>.dataChannel<347>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<38>
Project.unit<0>.dataChannel<348>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<37>
Project.unit<0>.dataChannel<349>=Inst_multichnlTDC Chnl_3_inst ChnlFifoFull
Project.unit<0>.dataChannel<34>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<3>
Project.unit<0>.dataChannel<350>=Inst_multichnlTDC Chnl_3_inst ChnlFifoAlmostFull
Project.unit<0>.dataChannel<351>=Inst_multichnlTDC Chnl_3_inst ChnlFifoEmpty
Project.unit<0>.dataChannel<352>=Inst_multichnlTDC Chnl_3_inst ChnlFifoProgFull
Project.unit<0>.dataChannel<353>=Inst_multichnlTDC Chnl_3_inst Token_out
Project.unit<0>.dataChannel<354>=Inst_multichnlTDC Chnl_3_inst ChnlFifoRdEn
Project.unit<0>.dataChannel<355>=Inst_multichnlTDC Chnl_3_inst RdFifoWren
Project.unit<0>.dataChannel<356>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<29>
Project.unit<0>.dataChannel<357>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<28>
Project.unit<0>.dataChannel<358>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<27>
Project.unit<0>.dataChannel<359>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<26>
Project.unit<0>.dataChannel<35>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<2>
Project.unit<0>.dataChannel<360>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<25>
Project.unit<0>.dataChannel<361>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<24>
Project.unit<0>.dataChannel<362>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<23>
Project.unit<0>.dataChannel<363>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<22>
Project.unit<0>.dataChannel<364>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<21>
Project.unit<0>.dataChannel<365>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<20>
Project.unit<0>.dataChannel<366>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<19>
Project.unit<0>.dataChannel<367>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<18>
Project.unit<0>.dataChannel<368>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<17>
Project.unit<0>.dataChannel<369>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<16>
Project.unit<0>.dataChannel<36>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<1>
Project.unit<0>.dataChannel<370>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<15>
Project.unit<0>.dataChannel<371>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<14>
Project.unit<0>.dataChannel<372>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<13>
Project.unit<0>.dataChannel<373>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<12>
Project.unit<0>.dataChannel<374>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<11>
Project.unit<0>.dataChannel<375>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<10>
Project.unit<0>.dataChannel<376>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<9>
Project.unit<0>.dataChannel<377>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<8>
Project.unit<0>.dataChannel<378>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<7>
Project.unit<0>.dataChannel<379>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<6>
Project.unit<0>.dataChannel<37>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<0>
Project.unit<0>.dataChannel<380>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<5>
Project.unit<0>.dataChannel<381>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<4>
Project.unit<0>.dataChannel<382>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<3>
Project.unit<0>.dataChannel<383>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<2>
Project.unit<0>.dataChannel<384>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<1>
Project.unit<0>.dataChannel<385>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<0>
Project.unit<0>.dataChannel<386>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst rst
Project.unit<0>.dataChannel<387>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst wr_clk
Project.unit<0>.dataChannel<388>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst rd_clk
Project.unit<0>.dataChannel<389>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst wr_en
Project.unit<0>.dataChannel<38>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst rst
Project.unit<0>.dataChannel<390>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst rd_en
Project.unit<0>.dataChannel<391>=Inst_multichnlTDC Chnl_3_inst ChnlFifoWrite
Project.unit<0>.dataChannel<392>=Inst_multichnlTDC Chnl_3_inst Cout
Project.unit<0>.dataChannel<393>=Inst_multichnlTDC Chnl_3_inst Clk
Project.unit<0>.dataChannel<394>=Inst_multichnlTDC Chnl_3_inst InvClk
Project.unit<0>.dataChannel<395>=Inst_multichnlTDC Chnl_3_inst FifoClk
Project.unit<0>.dataChannel<396>=Inst_multichnlTDC Chnl_3_inst HitIn
Project.unit<0>.dataChannel<397>=Inst_multichnlTDC Chnl_3_inst fifo_rst
Project.unit<0>.dataChannel<398>=Inst_multichnlTDC Chnl_3_inst SysEnable
Project.unit<0>.dataChannel<399>=Inst_multichnlTDC Chnl_3_inst fifo_rst
Project.unit<0>.dataChannel<39>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst wr_clk
Project.unit<0>.dataChannel<3>=Inst_multichnlTDC tdc_frame_fifo_inst rd_clk
Project.unit<0>.dataChannel<400>=Inst_multichnlTDC Chnl_3_inst Token_in
Project.unit<0>.dataChannel<401>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<7>
Project.unit<0>.dataChannel<402>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<6>
Project.unit<0>.dataChannel<403>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<5>
Project.unit<0>.dataChannel<404>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<4>
Project.unit<0>.dataChannel<405>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<3>
Project.unit<0>.dataChannel<406>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<2>
Project.unit<0>.dataChannel<407>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<1>
Project.unit<0>.dataChannel<408>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<0>
Project.unit<0>.dataChannel<409>=Inst_multichnlTDC Chnl_3_inst ChnlFifoEmpty
Project.unit<0>.dataChannel<40>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst rd_clk
Project.unit<0>.dataChannel<410>=Inst_multichnlTDC Chnl_3_inst ChnlFifoRdEn
Project.unit<0>.dataChannel<411>=Inst_multichnlTDC tdc_frame_fifo_inst rst
Project.unit<0>.dataChannel<412>=Inst_multichnlTDC tdc_frame_fifo_inst wr_en
Project.unit<0>.dataChannel<413>=Inst_multichnlTDC tdc_frame_fifo_inst rd_en
Project.unit<0>.dataChannel<414>=Inst_multichnlTDC tdc_frame_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.wsts/ram_almost_full_i
Project.unit<0>.dataChannel<415>=Inst_multichnlTDC tdc_frame_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/gras.rsts/gae.ram_almost_empty_i
Project.unit<0>.dataChannel<416>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst rst
Project.unit<0>.dataChannel<417>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst wr_en
Project.unit<0>.dataChannel<418>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst rd_en
Project.unit<0>.dataChannel<419>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.wsts/ram_almost_full_i
Project.unit<0>.dataChannel<41>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst wr_en
Project.unit<0>.dataChannel<420>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.dataChannel<421>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In1
Project.unit<0>.dataChannel<422>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In2
Project.unit<0>.dataChannel<423>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In3
Project.unit<0>.dataChannel<424>=Inst_multichnlTDC Inst_FramePack frame_en
Project.unit<0>.dataChannel<425>=Inst_multichnlTDC Inst_FramePack tdc_frame_fifo_almost_empty
Project.unit<0>.dataChannel<426>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_en
Project.unit<0>.dataChannel<427>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_almost_full
Project.unit<0>.dataChannel<428>=Inst_multichnlTDC Inst_FramePack crc_en
Project.unit<0>.dataChannel<429>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_wr_en
Project.unit<0>.dataChannel<42>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst rd_en
Project.unit<0>.dataChannel<430>=Inst_multichnlTDC Inst_FramePack tdc_frame_fifo_rd_en_sig
Project.unit<0>.dataChannel<431>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<15>
Project.unit<0>.dataChannel<432>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<14>
Project.unit<0>.dataChannel<433>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<13>
Project.unit<0>.dataChannel<434>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<12>
Project.unit<0>.dataChannel<435>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<11>
Project.unit<0>.dataChannel<436>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<10>
Project.unit<0>.dataChannel<437>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<9>
Project.unit<0>.dataChannel<438>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<8>
Project.unit<0>.dataChannel<439>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<7>
Project.unit<0>.dataChannel<43>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<15>
Project.unit<0>.dataChannel<440>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<6>
Project.unit<0>.dataChannel<441>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<5>
Project.unit<0>.dataChannel<442>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<4>
Project.unit<0>.dataChannel<443>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<3>
Project.unit<0>.dataChannel<444>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<2>
Project.unit<0>.dataChannel<445>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<1>
Project.unit<0>.dataChannel<446>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<0>
Project.unit<0>.dataChannel<447>=Inst_multichnlTDC sdram_cpldif_fifo_inst rst
Project.unit<0>.dataChannel<448>=Inst_multichnlTDC sdram_cpldif_fifo_inst wr_clk
Project.unit<0>.dataChannel<449>=Inst_multichnlTDC sdram_cpldif_fifo_inst rd_clk
Project.unit<0>.dataChannel<44>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<14>
Project.unit<0>.dataChannel<450>=Inst_multichnlTDC sdram_cpldif_fifo_inst wr_en
Project.unit<0>.dataChannel<451>=Inst_multichnlTDC sdram_cpldif_fifo_inst rd_en
Project.unit<0>.dataChannel<452>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<31>
Project.unit<0>.dataChannel<453>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<30>
Project.unit<0>.dataChannel<454>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<29>
Project.unit<0>.dataChannel<455>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<28>
Project.unit<0>.dataChannel<456>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<27>
Project.unit<0>.dataChannel<457>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<26>
Project.unit<0>.dataChannel<458>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<25>
Project.unit<0>.dataChannel<459>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<24>
Project.unit<0>.dataChannel<45>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<13>
Project.unit<0>.dataChannel<460>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<23>
Project.unit<0>.dataChannel<461>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<22>
Project.unit<0>.dataChannel<462>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<21>
Project.unit<0>.dataChannel<463>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<20>
Project.unit<0>.dataChannel<464>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<19>
Project.unit<0>.dataChannel<465>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<18>
Project.unit<0>.dataChannel<466>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<17>
Project.unit<0>.dataChannel<467>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<16>
Project.unit<0>.dataChannel<468>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<15>
Project.unit<0>.dataChannel<469>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<14>
Project.unit<0>.dataChannel<46>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<12>
Project.unit<0>.dataChannel<470>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<13>
Project.unit<0>.dataChannel<471>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<12>
Project.unit<0>.dataChannel<472>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<11>
Project.unit<0>.dataChannel<473>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<10>
Project.unit<0>.dataChannel<474>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<9>
Project.unit<0>.dataChannel<475>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<8>
Project.unit<0>.dataChannel<476>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<7>
Project.unit<0>.dataChannel<477>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<6>
Project.unit<0>.dataChannel<478>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<5>
Project.unit<0>.dataChannel<479>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<4>
Project.unit<0>.dataChannel<47>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<11>
Project.unit<0>.dataChannel<480>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<3>
Project.unit<0>.dataChannel<481>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<2>
Project.unit<0>.dataChannel<482>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<1>
Project.unit<0>.dataChannel<483>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<0>
Project.unit<0>.dataChannel<484>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<11>
Project.unit<0>.dataChannel<485>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<10>
Project.unit<0>.dataChannel<486>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<9>
Project.unit<0>.dataChannel<487>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<8>
Project.unit<0>.dataChannel<488>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<7>
Project.unit<0>.dataChannel<489>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<6>
Project.unit<0>.dataChannel<48>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<10>
Project.unit<0>.dataChannel<490>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<5>
Project.unit<0>.dataChannel<491>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<4>
Project.unit<0>.dataChannel<492>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<3>
Project.unit<0>.dataChannel<493>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<2>
Project.unit<0>.dataChannel<494>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<1>
Project.unit<0>.dataChannel<495>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<0>
Project.unit<0>.dataChannel<496>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.wsts/ram_almost_full_i
Project.unit<0>.dataChannel<497>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/gras.rsts/gae.ram_almost_empty_i
Project.unit<0>.dataChannel<498>=Inst_multichnlTDC Inst_RAMctrl READ_RAM_DONE
Project.unit<0>.dataChannel<499>=Inst_multichnlTDC Inst_RAMctrl WRITE_RAM_READY
Project.unit<0>.dataChannel<49>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<9>
Project.unit<0>.dataChannel<4>=Inst_multichnlTDC tdc_frame_fifo_inst wr_en
Project.unit<0>.dataChannel<500>=Inst_multichnlTDC Inst_RAMctrl Read_Enable
Project.unit<0>.dataChannel<501>=Inst_multichnlTDC Inst_RAMctrl READ_RAM_READY
Project.unit<0>.dataChannel<502>=Inst_multichnlTDC Inst_RAMctrl READ_RAM_EN
Project.unit<0>.dataChannel<503>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_OUTEN_inv
Project.unit<0>.dataChannel<504>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<15>
Project.unit<0>.dataChannel<505>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<14>
Project.unit<0>.dataChannel<506>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<13>
Project.unit<0>.dataChannel<507>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<12>
Project.unit<0>.dataChannel<508>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<11>
Project.unit<0>.dataChannel<509>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<10>
Project.unit<0>.dataChannel<50>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<8>
Project.unit<0>.dataChannel<510>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<9>
Project.unit<0>.dataChannel<511>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<8>
Project.unit<0>.dataChannel<512>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<7>
Project.unit<0>.dataChannel<513>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<6>
Project.unit<0>.dataChannel<514>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<5>
Project.unit<0>.dataChannel<515>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<4>
Project.unit<0>.dataChannel<516>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<3>
Project.unit<0>.dataChannel<517>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<2>
Project.unit<0>.dataChannel<518>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<1>
Project.unit<0>.dataChannel<519>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<0>
Project.unit<0>.dataChannel<51>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<7>
Project.unit<0>.dataChannel<52>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<6>
Project.unit<0>.dataChannel<53>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<5>
Project.unit<0>.dataChannel<54>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<4>
Project.unit<0>.dataChannel<55>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<3>
Project.unit<0>.dataChannel<56>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<2>
Project.unit<0>.dataChannel<57>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<1>
Project.unit<0>.dataChannel<58>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<0>
Project.unit<0>.dataChannel<59>=Inst_multichnlTDC Inst_RAMctrl testsignal<26>
Project.unit<0>.dataChannel<5>=Inst_multichnlTDC tdc_frame_fifo_inst rd_en
Project.unit<0>.dataChannel<60>=Inst_multichnlTDC Inst_RAMctrl testsignal<25>
Project.unit<0>.dataChannel<61>=Inst_multichnlTDC Inst_RAMctrl testsignal<24>
Project.unit<0>.dataChannel<62>=Inst_multichnlTDC Inst_RAMctrl testsignal<23>
Project.unit<0>.dataChannel<63>=Inst_multichnlTDC Inst_RAMctrl testsignal<22>
Project.unit<0>.dataChannel<64>=Inst_multichnlTDC Inst_RAMctrl testsignal<21>
Project.unit<0>.dataChannel<65>=Inst_multichnlTDC Inst_RAMctrl testsignal<20>
Project.unit<0>.dataChannel<66>=Inst_multichnlTDC Inst_RAMctrl testsignal<19>
Project.unit<0>.dataChannel<67>=Inst_multichnlTDC Inst_RAMctrl testsignal<18>
Project.unit<0>.dataChannel<68>=Inst_multichnlTDC Inst_RAMctrl testsignal<17>
Project.unit<0>.dataChannel<69>=Inst_multichnlTDC Inst_RAMctrl testsignal<16>
Project.unit<0>.dataChannel<6>=Inst_multichnlTDC tdc_frame_fifo_inst dout<15>
Project.unit<0>.dataChannel<70>=Inst_multichnlTDC Inst_RAMctrl testsignal<15>
Project.unit<0>.dataChannel<71>=Inst_multichnlTDC Inst_RAMctrl testsignal<14>
Project.unit<0>.dataChannel<72>=Inst_multichnlTDC Inst_RAMctrl testsignal<13>
Project.unit<0>.dataChannel<73>=Inst_multichnlTDC Inst_RAMctrl testsignal<12>
Project.unit<0>.dataChannel<74>=Inst_multichnlTDC Inst_RAMctrl testsignal<11>
Project.unit<0>.dataChannel<75>=Inst_multichnlTDC Inst_RAMctrl testsignal<10>
Project.unit<0>.dataChannel<76>=Inst_multichnlTDC Inst_RAMctrl testsignal<9>
Project.unit<0>.dataChannel<77>=Inst_multichnlTDC Inst_RAMctrl testsignal<8>
Project.unit<0>.dataChannel<78>=Inst_multichnlTDC Inst_RAMctrl testsignal<7>
Project.unit<0>.dataChannel<79>=Inst_multichnlTDC Inst_RAMctrl testsignal<6>
Project.unit<0>.dataChannel<7>=Inst_multichnlTDC tdc_frame_fifo_inst dout<14>
Project.unit<0>.dataChannel<80>=Inst_multichnlTDC Inst_RAMctrl testsignal<5>
Project.unit<0>.dataChannel<81>=Inst_multichnlTDC Inst_RAMctrl testsignal<4>
Project.unit<0>.dataChannel<82>=Inst_multichnlTDC Inst_RAMctrl testsignal<3>
Project.unit<0>.dataChannel<83>=Inst_multichnlTDC Inst_RAMctrl testsignal<2>
Project.unit<0>.dataChannel<84>=Inst_multichnlTDC Inst_RAMctrl testsignal<1>
Project.unit<0>.dataChannel<85>=Inst_multichnlTDC Inst_RAMctrl testsignal<0>
Project.unit<0>.dataChannel<86>=Inst_multichnlTDC Inst_RAMctrl INIT_DONE
Project.unit<0>.dataChannel<87>=Inst_multichnlTDC Inst_RAMctrl ACTIONFORBID
Project.unit<0>.dataChannel<88>=Inst_multichnlTDC Inst_RAMctrl READ_RAM_DONE
Project.unit<0>.dataChannel<89>=Inst_multichnlTDC Inst_RAMctrl WRITE_RAM_READY
Project.unit<0>.dataChannel<8>=Inst_multichnlTDC tdc_frame_fifo_inst dout<13>
Project.unit<0>.dataChannel<90>=Inst_multichnlTDC Inst_RAMctrl WRITE_RAM_DONE
Project.unit<0>.dataChannel<91>=Inst_multichnlTDC Inst_RAMctrl DQML
Project.unit<0>.dataChannel<92>=Inst_multichnlTDC Inst_RAMctrl DQMH
Project.unit<0>.dataChannel<93>=Inst_multichnlTDC Inst_RAMctrl nWE
Project.unit<0>.dataChannel<94>=Inst_multichnlTDC Inst_RAMctrl nCAS
Project.unit<0>.dataChannel<95>=Inst_multichnlTDC Inst_RAMctrl nRAS
Project.unit<0>.dataChannel<96>=Inst_multichnlTDC Inst_RAMctrl nCS
Project.unit<0>.dataChannel<97>=Inst_multichnlTDC Inst_RAMctrl CKE
Project.unit<0>.dataChannel<98>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<15>
Project.unit<0>.dataChannel<99>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<14>
Project.unit<0>.dataChannel<9>=Inst_multichnlTDC tdc_frame_fifo_inst dout<12>
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=443
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=Inst_multichnlTDC fifo_rst
Project.unit<0>.triggerChannel<0><100>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<11>
Project.unit<0>.triggerChannel<0><101>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<10>
Project.unit<0>.triggerChannel<0><102>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<9>
Project.unit<0>.triggerChannel<0><103>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<8>
Project.unit<0>.triggerChannel<0><104>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<7>
Project.unit<0>.triggerChannel<0><105>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<6>
Project.unit<0>.triggerChannel<0><106>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<5>
Project.unit<0>.triggerChannel<0><107>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<4>
Project.unit<0>.triggerChannel<0><108>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<3>
Project.unit<0>.triggerChannel<0><109>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<2>
Project.unit<0>.triggerChannel<0><10>=Inst_multichnlTDC tdc_frame_fifo_inst dout<11>
Project.unit<0>.triggerChannel<0><110>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<1>
Project.unit<0>.triggerChannel<0><111>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<0>
Project.unit<0>.triggerChannel<0><112>=Inst_multichnlTDC Inst_RAMctrl testsignal<26>
Project.unit<0>.triggerChannel<0><113>=Inst_multichnlTDC Inst_RAMctrl testsignal<25>
Project.unit<0>.triggerChannel<0><114>=Inst_multichnlTDC Inst_RAMctrl testsignal<24>
Project.unit<0>.triggerChannel<0><115>=Inst_multichnlTDC Inst_RAMctrl testsignal<23>
Project.unit<0>.triggerChannel<0><116>=Inst_multichnlTDC Inst_RAMctrl testsignal<22>
Project.unit<0>.triggerChannel<0><117>=Inst_multichnlTDC Inst_RAMctrl testsignal<21>
Project.unit<0>.triggerChannel<0><118>=Inst_multichnlTDC Inst_RAMctrl testsignal<20>
Project.unit<0>.triggerChannel<0><119>=Inst_multichnlTDC Inst_RAMctrl testsignal<19>
Project.unit<0>.triggerChannel<0><11>=Inst_multichnlTDC tdc_frame_fifo_inst dout<10>
Project.unit<0>.triggerChannel<0><120>=Inst_multichnlTDC Inst_RAMctrl testsignal<18>
Project.unit<0>.triggerChannel<0><121>=Inst_multichnlTDC Inst_RAMctrl testsignal<17>
Project.unit<0>.triggerChannel<0><122>=Inst_multichnlTDC Inst_RAMctrl testsignal<16>
Project.unit<0>.triggerChannel<0><123>=Inst_multichnlTDC Inst_RAMctrl testsignal<15>
Project.unit<0>.triggerChannel<0><124>=Inst_multichnlTDC Inst_RAMctrl testsignal<14>
Project.unit<0>.triggerChannel<0><125>=Inst_multichnlTDC Inst_RAMctrl testsignal<13>
Project.unit<0>.triggerChannel<0><126>=Inst_multichnlTDC Inst_RAMctrl testsignal<12>
Project.unit<0>.triggerChannel<0><127>=Inst_multichnlTDC Inst_RAMctrl testsignal<11>
Project.unit<0>.triggerChannel<0><128>=Inst_multichnlTDC Inst_RAMctrl testsignal<10>
Project.unit<0>.triggerChannel<0><129>=Inst_multichnlTDC Inst_RAMctrl testsignal<9>
Project.unit<0>.triggerChannel<0><12>=Inst_multichnlTDC tdc_frame_fifo_inst dout<9>
Project.unit<0>.triggerChannel<0><130>=Inst_multichnlTDC Inst_RAMctrl testsignal<8>
Project.unit<0>.triggerChannel<0><131>=Inst_multichnlTDC Inst_RAMctrl testsignal<7>
Project.unit<0>.triggerChannel<0><132>=Inst_multichnlTDC Inst_RAMctrl testsignal<6>
Project.unit<0>.triggerChannel<0><133>=Inst_multichnlTDC Inst_RAMctrl testsignal<5>
Project.unit<0>.triggerChannel<0><134>=Inst_multichnlTDC Inst_RAMctrl testsignal<4>
Project.unit<0>.triggerChannel<0><135>=Inst_multichnlTDC Inst_RAMctrl testsignal<3>
Project.unit<0>.triggerChannel<0><136>=Inst_multichnlTDC Inst_RAMctrl testsignal<2>
Project.unit<0>.triggerChannel<0><137>=Inst_multichnlTDC Inst_RAMctrl testsignal<1>
Project.unit<0>.triggerChannel<0><138>=Inst_multichnlTDC Inst_RAMctrl testsignal<0>
Project.unit<0>.triggerChannel<0><139>=Inst_multichnlTDC Inst_RAMctrl INIT_DONE
Project.unit<0>.triggerChannel<0><13>=Inst_multichnlTDC tdc_frame_fifo_inst dout<8>
Project.unit<0>.triggerChannel<0><140>=Inst_multichnlTDC Inst_RAMctrl ACTIONFORBID
Project.unit<0>.triggerChannel<0><141>=Inst_multichnlTDC Inst_RAMctrl READ_RAM_DONE
Project.unit<0>.triggerChannel<0><142>=Inst_multichnlTDC Inst_RAMctrl WRITE_RAM_READY
Project.unit<0>.triggerChannel<0><143>=Inst_multichnlTDC Inst_RAMctrl WRITE_RAM_DONE
Project.unit<0>.triggerChannel<0><144>=Inst_multichnlTDC Inst_RAMctrl DQML
Project.unit<0>.triggerChannel<0><145>=Inst_multichnlTDC Inst_RAMctrl DQMH
Project.unit<0>.triggerChannel<0><146>=Inst_multichnlTDC Inst_RAMctrl nWE
Project.unit<0>.triggerChannel<0><147>=Inst_multichnlTDC Inst_RAMctrl nCAS
Project.unit<0>.triggerChannel<0><148>=Inst_multichnlTDC Inst_RAMctrl nRAS
Project.unit<0>.triggerChannel<0><149>=Inst_multichnlTDC Inst_RAMctrl nCS
Project.unit<0>.triggerChannel<0><14>=Inst_multichnlTDC tdc_frame_fifo_inst dout<7>
Project.unit<0>.triggerChannel<0><150>=Inst_multichnlTDC Inst_RAMctrl CKE
Project.unit<0>.triggerChannel<0><15>=Inst_multichnlTDC tdc_frame_fifo_inst dout<6>
Project.unit<0>.triggerChannel<0><16>=Inst_multichnlTDC tdc_frame_fifo_inst dout<5>
Project.unit<0>.triggerChannel<0><17>=Inst_multichnlTDC tdc_frame_fifo_inst dout<4>
Project.unit<0>.triggerChannel<0><18>=Inst_multichnlTDC tdc_frame_fifo_inst dout<3>
Project.unit<0>.triggerChannel<0><19>=Inst_multichnlTDC tdc_frame_fifo_inst dout<2>
Project.unit<0>.triggerChannel<0><1>=Inst_multichnlTDC tdc_frame_fifo_inst rst
Project.unit<0>.triggerChannel<0><20>=Inst_multichnlTDC tdc_frame_fifo_inst dout<1>
Project.unit<0>.triggerChannel<0><21>=Inst_multichnlTDC tdc_frame_fifo_inst dout<0>
Project.unit<0>.triggerChannel<0><22>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<15>
Project.unit<0>.triggerChannel<0><23>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<14>
Project.unit<0>.triggerChannel<0><24>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<13>
Project.unit<0>.triggerChannel<0><25>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<12>
Project.unit<0>.triggerChannel<0><26>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<11>
Project.unit<0>.triggerChannel<0><27>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<10>
Project.unit<0>.triggerChannel<0><28>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<9>
Project.unit<0>.triggerChannel<0><29>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<8>
Project.unit<0>.triggerChannel<0><2>=Inst_multichnlTDC tdc_frame_fifo_inst wr_clk
Project.unit<0>.triggerChannel<0><30>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<7>
Project.unit<0>.triggerChannel<0><31>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<6>
Project.unit<0>.triggerChannel<0><32>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<5>
Project.unit<0>.triggerChannel<0><33>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<4>
Project.unit<0>.triggerChannel<0><34>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<3>
Project.unit<0>.triggerChannel<0><35>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<2>
Project.unit<0>.triggerChannel<0><36>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<1>
Project.unit<0>.triggerChannel<0><37>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst din<0>
Project.unit<0>.triggerChannel<0><38>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst rst
Project.unit<0>.triggerChannel<0><39>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst wr_clk
Project.unit<0>.triggerChannel<0><3>=Inst_multichnlTDC tdc_frame_fifo_inst rd_clk
Project.unit<0>.triggerChannel<0><40>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst rd_clk
Project.unit<0>.triggerChannel<0><41>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst wr_en
Project.unit<0>.triggerChannel<0><42>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst rd_en
Project.unit<0>.triggerChannel<0><43>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<15>
Project.unit<0>.triggerChannel<0><44>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<14>
Project.unit<0>.triggerChannel<0><45>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<13>
Project.unit<0>.triggerChannel<0><46>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<12>
Project.unit<0>.triggerChannel<0><47>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<11>
Project.unit<0>.triggerChannel<0><48>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<10>
Project.unit<0>.triggerChannel<0><49>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<9>
Project.unit<0>.triggerChannel<0><4>=Inst_multichnlTDC tdc_frame_fifo_inst wr_en
Project.unit<0>.triggerChannel<0><50>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<8>
Project.unit<0>.triggerChannel<0><51>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<7>
Project.unit<0>.triggerChannel<0><52>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<6>
Project.unit<0>.triggerChannel<0><53>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<5>
Project.unit<0>.triggerChannel<0><54>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<4>
Project.unit<0>.triggerChannel<0><55>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<3>
Project.unit<0>.triggerChannel<0><56>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<2>
Project.unit<0>.triggerChannel<0><57>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<1>
Project.unit<0>.triggerChannel<0><58>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst dout<0>
Project.unit<0>.triggerChannel<0><59>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<15>
Project.unit<0>.triggerChannel<0><5>=Inst_multichnlTDC tdc_frame_fifo_inst rd_en
Project.unit<0>.triggerChannel<0><60>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<14>
Project.unit<0>.triggerChannel<0><61>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<13>
Project.unit<0>.triggerChannel<0><62>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<12>
Project.unit<0>.triggerChannel<0><63>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<11>
Project.unit<0>.triggerChannel<0><64>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<10>
Project.unit<0>.triggerChannel<0><65>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<9>
Project.unit<0>.triggerChannel<0><66>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<8>
Project.unit<0>.triggerChannel<0><67>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<7>
Project.unit<0>.triggerChannel<0><68>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<6>
Project.unit<0>.triggerChannel<0><69>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<5>
Project.unit<0>.triggerChannel<0><6>=Inst_multichnlTDC tdc_frame_fifo_inst dout<15>
Project.unit<0>.triggerChannel<0><70>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<4>
Project.unit<0>.triggerChannel<0><71>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<3>
Project.unit<0>.triggerChannel<0><72>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<2>
Project.unit<0>.triggerChannel<0><73>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<1>
Project.unit<0>.triggerChannel<0><74>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<0>
Project.unit<0>.triggerChannel<0><75>=Inst_multichnlTDC sdram_cpldif_fifo_inst rst
Project.unit<0>.triggerChannel<0><76>=Inst_multichnlTDC sdram_cpldif_fifo_inst wr_clk
Project.unit<0>.triggerChannel<0><77>=Inst_multichnlTDC sdram_cpldif_fifo_inst rd_clk
Project.unit<0>.triggerChannel<0><78>=Inst_multichnlTDC sdram_cpldif_fifo_inst wr_en
Project.unit<0>.triggerChannel<0><79>=Inst_multichnlTDC sdram_cpldif_fifo_inst rd_en
Project.unit<0>.triggerChannel<0><7>=Inst_multichnlTDC tdc_frame_fifo_inst dout<14>
Project.unit<0>.triggerChannel<0><80>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<31>
Project.unit<0>.triggerChannel<0><81>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<30>
Project.unit<0>.triggerChannel<0><82>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<29>
Project.unit<0>.triggerChannel<0><83>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<28>
Project.unit<0>.triggerChannel<0><84>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<27>
Project.unit<0>.triggerChannel<0><85>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<26>
Project.unit<0>.triggerChannel<0><86>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<25>
Project.unit<0>.triggerChannel<0><87>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<24>
Project.unit<0>.triggerChannel<0><88>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<23>
Project.unit<0>.triggerChannel<0><89>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<22>
Project.unit<0>.triggerChannel<0><8>=Inst_multichnlTDC tdc_frame_fifo_inst dout<13>
Project.unit<0>.triggerChannel<0><90>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<21>
Project.unit<0>.triggerChannel<0><91>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<20>
Project.unit<0>.triggerChannel<0><92>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<19>
Project.unit<0>.triggerChannel<0><93>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<18>
Project.unit<0>.triggerChannel<0><94>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<17>
Project.unit<0>.triggerChannel<0><95>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<16>
Project.unit<0>.triggerChannel<0><96>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<15>
Project.unit<0>.triggerChannel<0><97>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<14>
Project.unit<0>.triggerChannel<0><98>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<13>
Project.unit<0>.triggerChannel<0><99>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<12>
Project.unit<0>.triggerChannel<0><9>=Inst_multichnlTDC tdc_frame_fifo_inst dout<12>
Project.unit<0>.triggerChannel<1><0>=Inst_cpld_if tdc_cpldif_fifo_wr_data<31>
Project.unit<0>.triggerChannel<1><10>=Inst_cpld_if tdc_cpldif_fifo_wr_data<21>
Project.unit<0>.triggerChannel<1><11>=Inst_cpld_if tdc_cpldif_fifo_wr_data<20>
Project.unit<0>.triggerChannel<1><12>=Inst_cpld_if tdc_cpldif_fifo_wr_data<19>
Project.unit<0>.triggerChannel<1><13>=Inst_cpld_if tdc_cpldif_fifo_wr_data<18>
Project.unit<0>.triggerChannel<1><14>=Inst_cpld_if tdc_cpldif_fifo_wr_data<17>
Project.unit<0>.triggerChannel<1><15>=Inst_cpld_if tdc_cpldif_fifo_wr_data<16>
Project.unit<0>.triggerChannel<1><16>=Inst_cpld_if tdc_cpldif_fifo_wr_data<15>
Project.unit<0>.triggerChannel<1><17>=Inst_cpld_if tdc_cpldif_fifo_wr_data<14>
Project.unit<0>.triggerChannel<1><18>=Inst_cpld_if tdc_cpldif_fifo_wr_data<13>
Project.unit<0>.triggerChannel<1><19>=Inst_cpld_if tdc_cpldif_fifo_wr_data<12>
Project.unit<0>.triggerChannel<1><1>=Inst_cpld_if tdc_cpldif_fifo_wr_data<30>
Project.unit<0>.triggerChannel<1><20>=Inst_cpld_if tdc_cpldif_fifo_wr_data<11>
Project.unit<0>.triggerChannel<1><21>=Inst_cpld_if tdc_cpldif_fifo_wr_data<10>
Project.unit<0>.triggerChannel<1><22>=Inst_cpld_if tdc_cpldif_fifo_wr_data<9>
Project.unit<0>.triggerChannel<1><23>=Inst_cpld_if tdc_cpldif_fifo_wr_data<8>
Project.unit<0>.triggerChannel<1><24>=Inst_cpld_if tdc_cpldif_fifo_wr_data<7>
Project.unit<0>.triggerChannel<1><25>=Inst_cpld_if tdc_cpldif_fifo_wr_data<6>
Project.unit<0>.triggerChannel<1><26>=Inst_cpld_if tdc_cpldif_fifo_wr_data<5>
Project.unit<0>.triggerChannel<1><27>=Inst_cpld_if tdc_cpldif_fifo_wr_data<4>
Project.unit<0>.triggerChannel<1><28>=Inst_cpld_if tdc_cpldif_fifo_wr_data<3>
Project.unit<0>.triggerChannel<1><29>=Inst_cpld_if tdc_cpldif_fifo_wr_data<2>
Project.unit<0>.triggerChannel<1><2>=Inst_cpld_if tdc_cpldif_fifo_wr_data<29>
Project.unit<0>.triggerChannel<1><30>=Inst_cpld_if tdc_cpldif_fifo_wr_data<1>
Project.unit<0>.triggerChannel<1><31>=Inst_cpld_if tdc_cpldif_fifo_wr_data<0>
Project.unit<0>.triggerChannel<1><3>=Inst_cpld_if tdc_cpldif_fifo_wr_data<28>
Project.unit<0>.triggerChannel<1><4>=Inst_cpld_if tdc_cpldif_fifo_wr_data<27>
Project.unit<0>.triggerChannel<1><5>=Inst_cpld_if tdc_cpldif_fifo_wr_data<26>
Project.unit<0>.triggerChannel<1><6>=Inst_cpld_if tdc_cpldif_fifo_wr_data<25>
Project.unit<0>.triggerChannel<1><7>=Inst_cpld_if tdc_cpldif_fifo_wr_data<24>
Project.unit<0>.triggerChannel<1><8>=Inst_cpld_if tdc_cpldif_fifo_wr_data<23>
Project.unit<0>.triggerChannel<1><9>=Inst_cpld_if tdc_cpldif_fifo_wr_data<22>
Project.unit<0>.triggerChannel<2><0>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<10>
Project.unit<0>.triggerChannel<2><10>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<0>
Project.unit<0>.triggerChannel<2><11>=Inst_multichnlTDC Inst_FramePack syn_frm_cnt<1>
Project.unit<0>.triggerChannel<2><12>=Inst_multichnlTDC Inst_FramePack syn_frm_cnt<0>
Project.unit<0>.triggerChannel<2><13>=Inst_multichnlTDC Inst_FramePack data_length_frm_cnt<1>
Project.unit<0>.triggerChannel<2><14>=Inst_multichnlTDC Inst_FramePack data_length_frm_cnt<0>
Project.unit<0>.triggerChannel<2><15>=Inst_multichnlTDC Inst_FramePack crc_frm_cnt<1>
Project.unit<0>.triggerChannel<2><16>=Inst_multichnlTDC Inst_FramePack crc_frm_cnt<0>
Project.unit<0>.triggerChannel<2><17>=Inst_multichnlTDC Inst_FramePack end_frm_cnt<1>
Project.unit<0>.triggerChannel<2><18>=Inst_multichnlTDC Inst_FramePack end_frm_cnt<0>
Project.unit<0>.triggerChannel<2><19>=Inst_multichnlTDC Inst_FramePack crc_rst_n
Project.unit<0>.triggerChannel<2><1>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<9>
Project.unit<0>.triggerChannel<2><20>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<0>
Project.unit<0>.triggerChannel<2><21>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<1>
Project.unit<0>.triggerChannel<2><22>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<2>
Project.unit<0>.triggerChannel<2><23>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<3>
Project.unit<0>.triggerChannel<2><24>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<4>
Project.unit<0>.triggerChannel<2><25>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<5>
Project.unit<0>.triggerChannel<2><26>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<6>
Project.unit<0>.triggerChannel<2><27>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<7>
Project.unit<0>.triggerChannel<2><28>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<8>
Project.unit<0>.triggerChannel<2><29>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<9>
Project.unit<0>.triggerChannel<2><2>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<8>
Project.unit<0>.triggerChannel<2><30>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<10>
Project.unit<0>.triggerChannel<2><31>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_data_count<11>
Project.unit<0>.triggerChannel<2><32>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd1-In
Project.unit<0>.triggerChannel<2><33>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd2-In
Project.unit<0>.triggerChannel<2><34>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In
Project.unit<0>.triggerChannel<2><35>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In1
Project.unit<0>.triggerChannel<2><36>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In2
Project.unit<0>.triggerChannel<2><37>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In3
Project.unit<0>.triggerChannel<2><38>=Inst_multichnlTDC Inst_FramePack tdc_frame_fifo_rd_en_sig
Project.unit<0>.triggerChannel<2><39>=Inst_sysmonitor sysmon_cpldif_data<4>
Project.unit<0>.triggerChannel<2><3>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<7>
Project.unit<0>.triggerChannel<2><40>=Inst_sysmonitor sysmon_cpldif_data<3>
Project.unit<0>.triggerChannel<2><41>=Inst_sysmonitor sysmon_cpldif_data<2>
Project.unit<0>.triggerChannel<2><42>=Inst_sysmonitor sysmon_cpldif_data<1>
Project.unit<0>.triggerChannel<2><43>=Inst_sysmonitor sysmon_cpldif_data<0>
Project.unit<0>.triggerChannel<2><44>=Inst_sysmonitor sysmon_ram_rd_addr<3>
Project.unit<0>.triggerChannel<2><45>=Inst_sysmonitor sysmon_ram_rd_addr<2>
Project.unit<0>.triggerChannel<2><46>=Inst_sysmonitor sysmon_ram_rd_addr<1>
Project.unit<0>.triggerChannel<2><47>=Inst_sysmonitor sysmon_ram_rd_addr<0>
Project.unit<0>.triggerChannel<2><4>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<6>
Project.unit<0>.triggerChannel<2><5>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<5>
Project.unit<0>.triggerChannel<2><6>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<4>
Project.unit<0>.triggerChannel<2><7>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<3>
Project.unit<0>.triggerChannel<2><8>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<2>
Project.unit<0>.triggerChannel<2><9>=Inst_multichnlTDC Inst_FramePack data_frm_wr_cnt<1>
Project.unit<0>.triggerChannel<3><0>=Inst_TIME time_local_gps_cur<15>
Project.unit<0>.triggerChannel<3><10>=Inst_TIME time_local_gps_cur<5>
Project.unit<0>.triggerChannel<3><11>=Inst_TIME time_local_gps_cur<4>
Project.unit<0>.triggerChannel<3><12>=Inst_TIME time_local_gps_cur<3>
Project.unit<0>.triggerChannel<3><13>=Inst_TIME time_local_gps_cur<2>
Project.unit<0>.triggerChannel<3><14>=Inst_TIME time_local_gps_cur<1>
Project.unit<0>.triggerChannel<3><15>=Inst_TIME time_local_gps_cur<0>
Project.unit<0>.triggerChannel<3><16>=Inst_TIME time_local_cur_sig<31>
Project.unit<0>.triggerChannel<3><17>=Inst_TIME time_local_cur_sig<30>
Project.unit<0>.triggerChannel<3><18>=Inst_TIME time_local_cur_sig<29>
Project.unit<0>.triggerChannel<3><19>=Inst_TIME time_local_cur_sig<28>
Project.unit<0>.triggerChannel<3><1>=Inst_TIME time_local_gps_cur<14>
Project.unit<0>.triggerChannel<3><20>=Inst_TIME time_local_cur_sig<27>
Project.unit<0>.triggerChannel<3><21>=Inst_TIME time_local_cur_sig<26>
Project.unit<0>.triggerChannel<3><22>=Inst_TIME time_local_cur_sig<25>
Project.unit<0>.triggerChannel<3><23>=Inst_TIME time_local_cur_sig<24>
Project.unit<0>.triggerChannel<3><24>=Inst_TIME time_local_cur_sig<23>
Project.unit<0>.triggerChannel<3><25>=Inst_TIME time_local_cur_sig<22>
Project.unit<0>.triggerChannel<3><26>=Inst_TIME time_local_cur_sig<21>
Project.unit<0>.triggerChannel<3><27>=Inst_TIME time_local_cur_sig<20>
Project.unit<0>.triggerChannel<3><28>=Inst_TIME time_local_cur_sig<19>
Project.unit<0>.triggerChannel<3><29>=Inst_TIME time_local_cur_sig<18>
Project.unit<0>.triggerChannel<3><2>=Inst_TIME time_local_gps_cur<13>
Project.unit<0>.triggerChannel<3><30>=Inst_TIME time_local_cur_sig<17>
Project.unit<0>.triggerChannel<3><31>=Inst_TIME time_local_cur_sig<16>
Project.unit<0>.triggerChannel<3><32>=Inst_TIME time_local_cur_sig<15>
Project.unit<0>.triggerChannel<3><33>=Inst_TIME time_local_cur_sig<14>
Project.unit<0>.triggerChannel<3><34>=Inst_TIME time_local_cur_sig<13>
Project.unit<0>.triggerChannel<3><35>=Inst_TIME time_local_cur_sig<12>
Project.unit<0>.triggerChannel<3><36>=Inst_TIME time_local_cur_sig<11>
Project.unit<0>.triggerChannel<3><37>=Inst_TIME time_local_cur_sig<10>
Project.unit<0>.triggerChannel<3><38>=Inst_TIME time_local_cur_sig<9>
Project.unit<0>.triggerChannel<3><39>=Inst_TIME time_local_cur_sig<8>
Project.unit<0>.triggerChannel<3><3>=Inst_TIME time_local_gps_cur<12>
Project.unit<0>.triggerChannel<3><40>=Inst_TIME time_local_cur_sig<7>
Project.unit<0>.triggerChannel<3><41>=Inst_TIME time_local_cur_sig<6>
Project.unit<0>.triggerChannel<3><42>=Inst_TIME time_local_cur_sig<5>
Project.unit<0>.triggerChannel<3><43>=Inst_TIME time_local_cur_sig<4>
Project.unit<0>.triggerChannel<3><44>=Inst_TIME time_local_cur_sig<3>
Project.unit<0>.triggerChannel<3><45>=Inst_TIME time_local_cur_sig<2>
Project.unit<0>.triggerChannel<3><46>=Inst_TIME time_local_cur_sig<1>
Project.unit<0>.triggerChannel<3><47>=Inst_TIME time_local_cur_sig<0>
Project.unit<0>.triggerChannel<3><48>=Inst_TIME time_reg_given_l<31>
Project.unit<0>.triggerChannel<3><49>=Inst_TIME time_reg_given_l<30>
Project.unit<0>.triggerChannel<3><4>=Inst_TIME time_local_gps_cur<11>
Project.unit<0>.triggerChannel<3><50>=Inst_TIME time_reg_given_l<29>
Project.unit<0>.triggerChannel<3><51>=Inst_TIME time_reg_given_l<28>
Project.unit<0>.triggerChannel<3><52>=Inst_TIME time_reg_given_l<27>
Project.unit<0>.triggerChannel<3><53>=Inst_TIME time_reg_given_l<26>
Project.unit<0>.triggerChannel<3><54>=Inst_TIME time_reg_given_l<25>
Project.unit<0>.triggerChannel<3><55>=Inst_TIME time_reg_given_l<24>
Project.unit<0>.triggerChannel<3><56>=Inst_TIME time_reg_given_l<23>
Project.unit<0>.triggerChannel<3><57>=Inst_TIME time_reg_given_l<22>
Project.unit<0>.triggerChannel<3><58>=Inst_TIME time_reg_given_l<21>
Project.unit<0>.triggerChannel<3><59>=Inst_TIME time_reg_given_l<20>
Project.unit<0>.triggerChannel<3><5>=Inst_TIME time_local_gps_cur<10>
Project.unit<0>.triggerChannel<3><60>=Inst_TIME time_reg_given_l<19>
Project.unit<0>.triggerChannel<3><61>=Inst_TIME time_reg_given_l<18>
Project.unit<0>.triggerChannel<3><62>=Inst_TIME time_reg_given_l<17>
Project.unit<0>.triggerChannel<3><63>=Inst_TIME time_reg_given_l<16>
Project.unit<0>.triggerChannel<3><64>=Inst_TIME time_reg_given_l<15>
Project.unit<0>.triggerChannel<3><65>=Inst_TIME time_reg_given_l<14>
Project.unit<0>.triggerChannel<3><66>=Inst_TIME time_reg_given_l<13>
Project.unit<0>.triggerChannel<3><67>=Inst_TIME time_reg_given_l<12>
Project.unit<0>.triggerChannel<3><68>=Inst_TIME time_reg_given_l<11>
Project.unit<0>.triggerChannel<3><69>=Inst_TIME time_reg_given_l<10>
Project.unit<0>.triggerChannel<3><6>=Inst_TIME time_local_gps_cur<9>
Project.unit<0>.triggerChannel<3><70>=Inst_TIME time_reg_given_l<9>
Project.unit<0>.triggerChannel<3><71>=Inst_TIME time_reg_given_l<8>
Project.unit<0>.triggerChannel<3><72>=Inst_TIME time_reg_given_l<7>
Project.unit<0>.triggerChannel<3><73>=Inst_TIME time_reg_given_l<6>
Project.unit<0>.triggerChannel<3><74>=Inst_TIME time_reg_given_l<5>
Project.unit<0>.triggerChannel<3><75>=Inst_TIME time_reg_given_l<4>
Project.unit<0>.triggerChannel<3><76>=Inst_TIME time_reg_given_l<3>
Project.unit<0>.triggerChannel<3><77>=Inst_TIME time_reg_given_l<2>
Project.unit<0>.triggerChannel<3><78>=Inst_TIME time_reg_given_l<1>
Project.unit<0>.triggerChannel<3><79>=Inst_TIME time_reg_given_l<0>
Project.unit<0>.triggerChannel<3><7>=Inst_TIME time_local_gps_cur<8>
Project.unit<0>.triggerChannel<3><80>=Inst_TIME gps_pps_syn_pulse
Project.unit<0>.triggerChannel<3><81>=Inst_TIME gps_pps_ok
Project.unit<0>.triggerChannel<3><82>=Inst_TIME gps_pps_ok_cnt<1>
Project.unit<0>.triggerChannel<3><83>=Inst_TIME gps_pps_ok_cnt<0>
Project.unit<0>.triggerChannel<3><84>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<15>
Project.unit<0>.triggerChannel<3><85>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<14>
Project.unit<0>.triggerChannel<3><86>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<13>
Project.unit<0>.triggerChannel<3><87>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<12>
Project.unit<0>.triggerChannel<3><88>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<11>
Project.unit<0>.triggerChannel<3><89>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<10>
Project.unit<0>.triggerChannel<3><8>=Inst_TIME time_local_gps_cur<7>
Project.unit<0>.triggerChannel<3><90>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<9>
Project.unit<0>.triggerChannel<3><91>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<8>
Project.unit<0>.triggerChannel<3><92>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<7>
Project.unit<0>.triggerChannel<3><93>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<6>
Project.unit<0>.triggerChannel<3><94>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<5>
Project.unit<0>.triggerChannel<3><95>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<4>
Project.unit<0>.triggerChannel<3><96>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<3>
Project.unit<0>.triggerChannel<3><97>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<2>
Project.unit<0>.triggerChannel<3><98>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<1>
Project.unit<0>.triggerChannel<3><99>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DOUT<0>
Project.unit<0>.triggerChannel<3><9>=Inst_TIME time_local_gps_cur<6>
Project.unit<0>.triggerChannel<4><0>=Inst_multichnlTDC Chnl_2_inst fifo_rst
Project.unit<0>.triggerChannel<4><10>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<44>
Project.unit<0>.triggerChannel<4><11>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<43>
Project.unit<0>.triggerChannel<4><12>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<42>
Project.unit<0>.triggerChannel<4><13>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<41>
Project.unit<0>.triggerChannel<4><14>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<40>
Project.unit<0>.triggerChannel<4><15>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<39>
Project.unit<0>.triggerChannel<4><16>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<38>
Project.unit<0>.triggerChannel<4><17>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<37>
Project.unit<0>.triggerChannel<4><18>=Inst_multichnlTDC Chnl_3_inst ChnlFifoFull
Project.unit<0>.triggerChannel<4><19>=Inst_multichnlTDC Chnl_3_inst ChnlFifoAlmostFull
Project.unit<0>.triggerChannel<4><1>=Inst_multichnlTDC Chnl_2_inst SysEnable
Project.unit<0>.triggerChannel<4><20>=Inst_multichnlTDC Chnl_3_inst ChnlFifoEmpty
Project.unit<0>.triggerChannel<4><21>=Inst_multichnlTDC Chnl_3_inst ChnlFifoProgFull
Project.unit<0>.triggerChannel<4><22>=Inst_multichnlTDC Chnl_3_inst Token_out
Project.unit<0>.triggerChannel<4><23>=Inst_multichnlTDC Chnl_3_inst ChnlFifoRdEn
Project.unit<0>.triggerChannel<4><24>=Inst_multichnlTDC Chnl_3_inst RdFifoWren
Project.unit<0>.triggerChannel<4><25>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<29>
Project.unit<0>.triggerChannel<4><26>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<28>
Project.unit<0>.triggerChannel<4><27>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<27>
Project.unit<0>.triggerChannel<4><28>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<26>
Project.unit<0>.triggerChannel<4><29>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<25>
Project.unit<0>.triggerChannel<4><2>=Inst_multichnlTDC Chnl_2_inst fifo_rst
Project.unit<0>.triggerChannel<4><30>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<24>
Project.unit<0>.triggerChannel<4><31>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<23>
Project.unit<0>.triggerChannel<4><32>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<22>
Project.unit<0>.triggerChannel<4><33>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<21>
Project.unit<0>.triggerChannel<4><34>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<20>
Project.unit<0>.triggerChannel<4><35>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<19>
Project.unit<0>.triggerChannel<4><36>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<18>
Project.unit<0>.triggerChannel<4><37>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<17>
Project.unit<0>.triggerChannel<4><38>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<16>
Project.unit<0>.triggerChannel<4><39>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<15>
Project.unit<0>.triggerChannel<4><3>=Inst_multichnlTDC Chnl_2_inst Token_in
Project.unit<0>.triggerChannel<4><40>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<14>
Project.unit<0>.triggerChannel<4><41>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<13>
Project.unit<0>.triggerChannel<4><42>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<12>
Project.unit<0>.triggerChannel<4><43>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<11>
Project.unit<0>.triggerChannel<4><44>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<10>
Project.unit<0>.triggerChannel<4><45>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<9>
Project.unit<0>.triggerChannel<4><46>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<8>
Project.unit<0>.triggerChannel<4><47>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<7>
Project.unit<0>.triggerChannel<4><48>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<6>
Project.unit<0>.triggerChannel<4><49>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<5>
Project.unit<0>.triggerChannel<4><4>=Inst_multichnlTDC Chnl_2_inst HitIn
Project.unit<0>.triggerChannel<4><50>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<4>
Project.unit<0>.triggerChannel<4><51>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<3>
Project.unit<0>.triggerChannel<4><52>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<2>
Project.unit<0>.triggerChannel<4><53>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<1>
Project.unit<0>.triggerChannel<4><54>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<0>
Project.unit<0>.triggerChannel<4><55>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst rst
Project.unit<0>.triggerChannel<4><56>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst wr_clk
Project.unit<0>.triggerChannel<4><57>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst rd_clk
Project.unit<0>.triggerChannel<4><58>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst wr_en
Project.unit<0>.triggerChannel<4><59>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst rd_en
Project.unit<0>.triggerChannel<4><5>=Inst_multichnlTDC Chnl_2_inst ChnlFifoWrite
Project.unit<0>.triggerChannel<4><60>=Inst_multichnlTDC Chnl_3_inst ChnlFifoWrite
Project.unit<0>.triggerChannel<4><61>=Inst_multichnlTDC Chnl_3_inst Cout
Project.unit<0>.triggerChannel<4><62>=Inst_multichnlTDC Chnl_3_inst Clk
Project.unit<0>.triggerChannel<4><63>=Inst_multichnlTDC Chnl_3_inst InvClk
Project.unit<0>.triggerChannel<4><64>=Inst_multichnlTDC Chnl_3_inst FifoClk
Project.unit<0>.triggerChannel<4><65>=Inst_multichnlTDC Chnl_3_inst HitIn
Project.unit<0>.triggerChannel<4><66>=Inst_multichnlTDC Chnl_3_inst fifo_rst
Project.unit<0>.triggerChannel<4><67>=Inst_multichnlTDC Chnl_3_inst SysEnable
Project.unit<0>.triggerChannel<4><68>=Inst_multichnlTDC Chnl_3_inst fifo_rst
Project.unit<0>.triggerChannel<4><69>=Inst_multichnlTDC Chnl_3_inst Token_in
Project.unit<0>.triggerChannel<4><6>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<48>
Project.unit<0>.triggerChannel<4><70>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<7>
Project.unit<0>.triggerChannel<4><71>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<6>
Project.unit<0>.triggerChannel<4><72>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<5>
Project.unit<0>.triggerChannel<4><73>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<4>
Project.unit<0>.triggerChannel<4><74>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<3>
Project.unit<0>.triggerChannel<4><75>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<2>
Project.unit<0>.triggerChannel<4><76>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<1>
Project.unit<0>.triggerChannel<4><77>=Inst_multichnlTDC Chnl_3_inst ChnlFifoDataCnts<0>
Project.unit<0>.triggerChannel<4><78>=Inst_multichnlTDC Chnl_3_inst ChnlFifoEmpty
Project.unit<0>.triggerChannel<4><79>=Inst_multichnlTDC Chnl_3_inst ChnlFifoRdEn
Project.unit<0>.triggerChannel<4><7>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<47>
Project.unit<0>.triggerChannel<4><8>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<46>
Project.unit<0>.triggerChannel<4><9>=Inst_multichnlTDC Chnl_2_inst chnlfifo_inst din<45>
Project.unit<0>.triggerChannel<5><0>=Inst_multichnlTDC tdc_frame_fifo_inst rst
Project.unit<0>.triggerChannel<5><10>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In1
Project.unit<0>.triggerChannel<5><11>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In2
Project.unit<0>.triggerChannel<5><12>=Inst_multichnlTDC Inst_FramePack pr_state_frm_FSM_FFd3-In3
Project.unit<0>.triggerChannel<5><13>=Inst_multichnlTDC Inst_FramePack frame_en
Project.unit<0>.triggerChannel<5><14>=Inst_multichnlTDC Inst_FramePack tdc_frame_fifo_almost_empty
Project.unit<0>.triggerChannel<5><15>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_rd_en
Project.unit<0>.triggerChannel<5><16>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_almost_full
Project.unit<0>.triggerChannel<5><17>=Inst_multichnlTDC Inst_FramePack crc_en
Project.unit<0>.triggerChannel<5><18>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_wr_en
Project.unit<0>.triggerChannel<5><19>=Inst_multichnlTDC Inst_FramePack tdc_frame_fifo_rd_en_sig
Project.unit<0>.triggerChannel<5><1>=Inst_multichnlTDC tdc_frame_fifo_inst wr_en
Project.unit<0>.triggerChannel<5><2>=Inst_multichnlTDC tdc_frame_fifo_inst rd_en
Project.unit<0>.triggerChannel<5><3>=Inst_multichnlTDC tdc_frame_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.wsts/ram_almost_full_i
Project.unit<0>.triggerChannel<5><4>=Inst_multichnlTDC tdc_frame_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/gras.rsts/gae.ram_almost_empty_i
Project.unit<0>.triggerChannel<5><5>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst rst
Project.unit<0>.triggerChannel<5><6>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst wr_en
Project.unit<0>.triggerChannel<5><7>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst rd_en
Project.unit<0>.triggerChannel<5><8>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.wsts/ram_almost_full_i
Project.unit<0>.triggerChannel<5><9>=Inst_multichnlTDC Inst_FramePack frame_sdram_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/gras.rsts/ram_empty_i
Project.unit<0>.triggerChannel<6><0>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<15>
Project.unit<0>.triggerChannel<6><10>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<5>
Project.unit<0>.triggerChannel<6><11>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<4>
Project.unit<0>.triggerChannel<6><12>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<3>
Project.unit<0>.triggerChannel<6><13>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<2>
Project.unit<0>.triggerChannel<6><14>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<1>
Project.unit<0>.triggerChannel<6><15>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<0>
Project.unit<0>.triggerChannel<6><16>=Inst_multichnlTDC sdram_cpldif_fifo_inst rst
Project.unit<0>.triggerChannel<6><17>=Inst_multichnlTDC sdram_cpldif_fifo_inst wr_clk
Project.unit<0>.triggerChannel<6><18>=Inst_multichnlTDC sdram_cpldif_fifo_inst rd_clk
Project.unit<0>.triggerChannel<6><19>=Inst_multichnlTDC sdram_cpldif_fifo_inst wr_en
Project.unit<0>.triggerChannel<6><1>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<14>
Project.unit<0>.triggerChannel<6><20>=Inst_multichnlTDC sdram_cpldif_fifo_inst rd_en
Project.unit<0>.triggerChannel<6><21>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<31>
Project.unit<0>.triggerChannel<6><22>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<30>
Project.unit<0>.triggerChannel<6><23>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<29>
Project.unit<0>.triggerChannel<6><24>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<28>
Project.unit<0>.triggerChannel<6><25>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<27>
Project.unit<0>.triggerChannel<6><26>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<26>
Project.unit<0>.triggerChannel<6><27>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<25>
Project.unit<0>.triggerChannel<6><28>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<24>
Project.unit<0>.triggerChannel<6><29>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<23>
Project.unit<0>.triggerChannel<6><2>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<13>
Project.unit<0>.triggerChannel<6><30>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<22>
Project.unit<0>.triggerChannel<6><31>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<21>
Project.unit<0>.triggerChannel<6><32>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<20>
Project.unit<0>.triggerChannel<6><33>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<19>
Project.unit<0>.triggerChannel<6><34>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<18>
Project.unit<0>.triggerChannel<6><35>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<17>
Project.unit<0>.triggerChannel<6><36>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<16>
Project.unit<0>.triggerChannel<6><37>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<15>
Project.unit<0>.triggerChannel<6><38>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<14>
Project.unit<0>.triggerChannel<6><39>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<13>
Project.unit<0>.triggerChannel<6><3>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<12>
Project.unit<0>.triggerChannel<6><40>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<12>
Project.unit<0>.triggerChannel<6><41>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<11>
Project.unit<0>.triggerChannel<6><42>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<10>
Project.unit<0>.triggerChannel<6><43>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<9>
Project.unit<0>.triggerChannel<6><44>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<8>
Project.unit<0>.triggerChannel<6><45>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<7>
Project.unit<0>.triggerChannel<6><46>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<6>
Project.unit<0>.triggerChannel<6><47>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<5>
Project.unit<0>.triggerChannel<6><48>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<4>
Project.unit<0>.triggerChannel<6><49>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<3>
Project.unit<0>.triggerChannel<6><4>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<11>
Project.unit<0>.triggerChannel<6><50>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<2>
Project.unit<0>.triggerChannel<6><51>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<1>
Project.unit<0>.triggerChannel<6><52>=Inst_multichnlTDC sdram_cpldif_fifo_inst dout<0>
Project.unit<0>.triggerChannel<6><53>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<11>
Project.unit<0>.triggerChannel<6><54>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<10>
Project.unit<0>.triggerChannel<6><55>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<9>
Project.unit<0>.triggerChannel<6><56>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<8>
Project.unit<0>.triggerChannel<6><57>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<7>
Project.unit<0>.triggerChannel<6><58>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<6>
Project.unit<0>.triggerChannel<6><59>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<5>
Project.unit<0>.triggerChannel<6><5>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<10>
Project.unit<0>.triggerChannel<6><60>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<4>
Project.unit<0>.triggerChannel<6><61>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<3>
Project.unit<0>.triggerChannel<6><62>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<2>
Project.unit<0>.triggerChannel<6><63>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<1>
Project.unit<0>.triggerChannel<6><64>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.gwdc0.wdc/wr_data_count_i<0>
Project.unit<0>.triggerChannel<6><65>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.wsts/ram_almost_full_i
Project.unit<0>.triggerChannel<6><66>=Inst_multichnlTDC sdram_cpldif_fifo_inst U0/xst_fifo_generator/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.rd/gras.rsts/gae.ram_almost_empty_i
Project.unit<0>.triggerChannel<6><67>=Inst_multichnlTDC Inst_RAMctrl READ_RAM_DONE
Project.unit<0>.triggerChannel<6><68>=Inst_multichnlTDC Inst_RAMctrl WRITE_RAM_READY
Project.unit<0>.triggerChannel<6><69>=Inst_multichnlTDC Inst_RAMctrl Read_Enable
Project.unit<0>.triggerChannel<6><6>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<9>
Project.unit<0>.triggerChannel<6><70>=Inst_multichnlTDC Inst_RAMctrl READ_RAM_READY
Project.unit<0>.triggerChannel<6><71>=Inst_multichnlTDC Inst_RAMctrl READ_RAM_EN
Project.unit<0>.triggerChannel<6><72>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_OUTEN_inv
Project.unit<0>.triggerChannel<6><73>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<15>
Project.unit<0>.triggerChannel<6><74>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<14>
Project.unit<0>.triggerChannel<6><75>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<13>
Project.unit<0>.triggerChannel<6><76>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<12>
Project.unit<0>.triggerChannel<6><77>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<11>
Project.unit<0>.triggerChannel<6><78>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<10>
Project.unit<0>.triggerChannel<6><79>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<9>
Project.unit<0>.triggerChannel<6><7>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<8>
Project.unit<0>.triggerChannel<6><80>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<8>
Project.unit<0>.triggerChannel<6><81>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<7>
Project.unit<0>.triggerChannel<6><82>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<6>
Project.unit<0>.triggerChannel<6><83>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<5>
Project.unit<0>.triggerChannel<6><84>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<4>
Project.unit<0>.triggerChannel<6><85>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<3>
Project.unit<0>.triggerChannel<6><86>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<2>
Project.unit<0>.triggerChannel<6><87>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<1>
Project.unit<0>.triggerChannel<6><88>=Inst_multichnlTDC Inst_RAMctrl sdram_inst DQ_REG<0>
Project.unit<0>.triggerChannel<6><8>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<7>
Project.unit<0>.triggerChannel<6><9>=Inst_multichnlTDC sdram_cpldif_fifo_inst din<6>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCount<5>=1
Project.unit<0>.triggerMatchCount<6>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchCountWidth<5><0>=0
Project.unit<0>.triggerMatchCountWidth<6><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerMatchType<5><0>=1
Project.unit<0>.triggerMatchType<6><0>=1
Project.unit<0>.triggerPortCount=7
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortIsData<5>=true
Project.unit<0>.triggerPortIsData<6>=true
Project.unit<0>.triggerPortWidth<0>=112
Project.unit<0>.triggerPortWidth<1>=32
Project.unit<0>.triggerPortWidth<2>=48
Project.unit<0>.triggerPortWidth<3>=84
Project.unit<0>.triggerPortWidth<4>=80
Project.unit<0>.triggerPortWidth<5>=20
Project.unit<0>.triggerPortWidth<6>=67
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
